services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./traefik/acme.json:/acme.json
    command:
      - "--api.insecure=true"  # Enable dashboard without auth (change in production)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"

  api:
    build: .
    volumes:
      - .:/app
      - ./torch-cache:/root/.cache/torch
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

networks:
  traefik-public:
    external: false

